openapi: 3.0.0
info:
  version: 1.0.0
  title: おおたかの森.comで利用するAPI
  license:
    name: otakanomoli.com
servers:
  - url: 'http://localhost:3000/v1'
    description: Development server
  - url: 'https://otakanomoli.com/v1'
    description: Production server
paths:
  /hospitals:
    get:
      summary: 病院検索のAPI
      operationId: hospitals
      tags:
        - hospitals
      parameters:
        - in: query
          name: howlongTakes
          description: 駅からの徒歩時間
          required: false
          schema:
            type: number
        - in: query
          name: department
          description: 診療科目
          required: false
          schema:
            type: string
            enum:
              - 0
              - 1
        - in: query
          name: openTime
          description: 現在空いているものを検索（2時間後まで）
          required: false
          schema:
            type: boolean
        - in: query
          name: openWeek
          description: 空いている曜日を検索
          required: false
          schema:
            type: boolean
        - in: query
          name: lat
          description: 検索位置の緯度（latitude）
          required: false
          schema:
            type: number
          example: 35.871782
        - in: query
          name: lng
          description: 検索位置の経度（longitude）
          required: false
          schema:
            type: number
          example: 139.925013
      responses:
        '200':
          description: 病院一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: ID
                    example: '1'
                  name:
                    type: string
                    description: 病院名
                    example: おおたかの森.com病院
                  postal_code:
                    type: string
                    description: 郵便番号
                    example: 270-0121
                  address:
                    type: string
                    description: 住所
                    example: 千葉県流山市西初石六丁目185-2
                  tel:
                    type: string
                    description: 電話番号
                    example: 04-7152-3333
                  url:
                    type: string
                    description: ホームページ
                    example: 'https://www.otakanomori-sc.com/'
                  am_start:
                    type: string
                    description: 午前開始時間
                    example: '09:00'
                  am_end:
                    type: string
                    description: 午前終了時間
                    example: '11:30'
                  pm_start:
                    type: string
                    description: 午後開始時間
                    example: '12:30'
                  pm_end:
                    type: string
                    description: 午後終了時間
                    example: '17:30'
                  reservation:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          description: |
                            予約方法:
                             * `0` - 電話予約
                             * `1` - インターネット予約
                          enum:
                            - '0'
                            - '1'
                          example: '0'
                        body:
                          type: string
                          description: 予約連絡先
                          example: 04-7152-3333
                  department:
                    type: array
                    description: 診療科
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: 内科
                        business_time_list:
                          type: array
                          items:
                            type: object
                            properties:
                              week:
                                type: string
                                description: >
                                  曜日: * `0` - 土曜日 * `1` - 日曜日 * `2` - 月曜日 * `3`
                                  - 火曜日 * `4` - 水曜日 * `5` - 木曜日 * `6` - 金曜日 *
                                  `7` - 祝日
                                enum:
                                  - '0'
                                  - '1'
                                  - '2'
                                  - '3'
                                  - '4'
                                  - '5'
                                  - '6'
                                  - '7'
                                  - '8'
                                example: '0'
                              start:
                                type: string
                                description: 開始時間
                                example: '09:00'
                              end:
                                type: string
                                description: 終了時間
                                example: '12:00'
              examples:
                hospitalsExample:
                  value:
                    name: おおたかの森.com病院
                    postal_code: 270-0121
                    address: 千葉県流山市西初石六丁目185-2
                    tel: 04-7152-3333
                    url: 'https://www.otakanomori-sc.com/'
                    reservation:
                      - type: '0'
                        body: 04-7152-3333
                      - type: '1'
                        body: 'https://www.otakanomori-sc.com/'
                    department:
                      - name: 内科
                        business_time_list:
                          - week: '0'
                            start: '09:00'
                            end: '12:00'
                          - week: '0'
                            start: '13:00'
                            end: '18:00'
                          - week: '7'
                            start: '13:00'
                            end: '18:00'
                      - name: 小児科
                        business_time_list:
                          - week: '0'
                            start: '09:00'
                            end: '12:00'
                          - week: '0'
                            start: '13:00'
                            end: '18:00'
components:
  schemas:
    hospitals:
      type: object
      properties:
        id:
          type: string
          description: ID
          example: '1'
        name:
          type: string
          description: 病院名
          example: おおたかの森.com病院
        postal_code:
          type: string
          description: 郵便番号
          example: 270-0121
        address:
          type: string
          description: 住所
          example: 千葉県流山市西初石六丁目185-2
        tel:
          type: string
          description: 電話番号
          example: 04-7152-3333
        url:
          type: string
          description: ホームページ
          example: 'https://www.otakanomori-sc.com/'
        am_start:
          type: string
          description: 午前開始時間
          example: '09:00'
        am_end:
          type: string
          description: 午前終了時間
          example: '11:30'
        pm_start:
          type: string
          description: 午後開始時間
          example: '12:30'
        pm_end:
          type: string
          description: 午後終了時間
          example: '17:30'
        reservation:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                description: |
                  予約方法:
                   * `0` - 電話予約
                   * `1` - インターネット予約
                enum:
                  - '0'
                  - '1'
                example: '0'
              body:
                type: string
                description: 予約連絡先
                example: 04-7152-3333
        department:
          type: array
          description: 診療科
          items:
            type: object
            properties:
              name:
                type: string
                example: 内科
              business_time_list:
                type: array
                items:
                  type: object
                  properties:
                    week:
                      type: string
                      description: >
                        曜日: * `0` - 土曜日 * `1` - 日曜日 * `2` - 月曜日 * `3` - 火曜日 *
                        `4` - 水曜日 * `5` - 木曜日 * `6` - 金曜日 * `7` - 祝日
                      enum:
                        - '0'
                        - '1'
                        - '2'
                        - '3'
                        - '4'
                        - '5'
                        - '6'
                        - '7'
                        - '8'
                      example: '0'
                    start:
                      type: string
                      description: 開始時間
                      example: '09:00'
                    end:
                      type: string
                      description: 終了時間
                      example: '12:00'
  examples:
    hospitalsExample:
      value:
        name: おおたかの森.com病院
        postal_code: 270-0121
        address: 千葉県流山市西初石六丁目185-2
        tel: 04-7152-3333
        url: 'https://www.otakanomori-sc.com/'
        reservation:
          - type: '0'
            body: 04-7152-3333
          - type: '1'
            body: 'https://www.otakanomori-sc.com/'
        department:
          - name: 内科
            business_time_list:
              - week: '0'
                start: '09:00'
                end: '12:00'
              - week: '0'
                start: '13:00'
                end: '18:00'
              - week: '7'
                start: '13:00'
                end: '18:00'
          - name: 小児科
            business_time_list:
              - week: '0'
                start: '09:00'
                end: '12:00'
              - week: '0'
                start: '13:00'
                end: '18:00'
