openapi: 3.0.0
info:
  version: 1.0.0
  title: Example Project
  license:
    name: MIT
servers:
  - url: 'http://localhost:3000/'
paths:
  /holidays:
    get:
      summary: 祝日リストのAPI
      operationId: holidays
      tags:
        - holidays
      responses:
        '200':
          description: 祝日リスト
          content:
            application/json:
              schema:
                type: object
                properties:
                  holiday_list:
                    type: array
                    items:
                      type: string
                      example:
                        - '20190501'
                        - '20190502'
                        - '20190503'
                        - '20190504'
                        - '20190505'
              examples:
                holidayExample:
                  value:
                    holiday_list:
                      - 20190501
                      - 20190502
                      - 20190503
                      - 20190504
                      - 20190505
components:
  schemas:
    holidays:
      type: object
      properties:
        holiday_list:
          type: array
          items:
            type: string
            example:
              - '20190501'
              - '20190502'
              - '20190503'
              - '20190504'
              - '20190505'
  examples:
    holidayExample:
      value:
        holiday_list:
          - 20190501
          - 20190502
          - 20190503
          - 20190504
          - 20190505
